// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM5oK-WQvOqs2abHH0OdZ8fuQwpeyVrN8',
    appId: '1:751983970188:web:56c46fa794b43b1988b8a9',
    messagingSenderId: '751983970188',
    projectId: 'valid-pagoda-390011',
    authDomain: 'valid-pagoda-390011.firebaseapp.com',
    storageBucket: 'valid-pagoda-390011.appspot.com',
    measurementId: 'G-97X5M7T86P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiY4fTk8tjEmtdfRbKpjimp2jgZ9UEDOQ',
    appId: '1:751983970188:android:e0ea248b91957f4088b8a9',
    messagingSenderId: '751983970188',
    projectId: 'valid-pagoda-390011',
    storageBucket: 'valid-pagoda-390011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArPGQyUHqerFEdZTTbrYFwyqtJPLM_oi0',
    appId: '1:751983970188:ios:05609bda4a59f73d88b8a9',
    messagingSenderId: '751983970188',
    projectId: 'valid-pagoda-390011',
    storageBucket: 'valid-pagoda-390011.appspot.com',
    iosClientId: '751983970188-22ios96vopmds175rl6lpg16uucs7346.apps.googleusercontent.com',
    iosBundleId: 'com.example.lottery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArPGQyUHqerFEdZTTbrYFwyqtJPLM_oi0',
    appId: '1:751983970188:ios:9ef841079e8eef0b88b8a9',
    messagingSenderId: '751983970188',
    projectId: 'valid-pagoda-390011',
    storageBucket: 'valid-pagoda-390011.appspot.com',
    iosClientId: '751983970188-matqn2gvhk951cngjl7pmfas9smks1or.apps.googleusercontent.com',
    iosBundleId: 'com.example.lottery.RunnerTests',
  );
}
